### ISSUE TITLE
カラム名をキャメルケースで定義した場合の挙動について

### ISSUE THREAD

**Issue by tekihei2317** [orisano/sqlc-gen-typescript-d1#1]
現在、個人開発プロジェクトのデータベースをFirestoreからCloudflare D1に移行しており、`sqlc-gen-ts-d1`を使用させていただいております。
https://github.com/tekihei2317/type-challenges-judge/pull/17

テーブルのカラム名をキャメルケースで定義しているのですが、想定外の挙動があったのでIssueを作成しました。

カラム名をキャメルケースで定義した場合、SELECTのクエリから生成したカラムの型は小文字になりますが、実際の値はキャメルケースで返ってきます。

### 環境

```tsx
// versions:
//   sqlc v1.19.1
//   sqlc-gen-ts-d1 v0.0.0-a@254c24db5bcb2e1e16559e7f8498d7fa673ada31
```

### 再現方法

こちらのリポジトリで再現しました。https://github.com/tekihei2317/sqlc-playground

schema.sql

```sql
CREATE TABLE User (
  id INTEGER NOT NULL PRIMARY KEY,
  screenName TEXT NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
```

query.sql

```sql
-- name: GetAllUsers :many
select * from User;
```

querier.ts

```tsx
import { D1Database, D1Result } from "@cloudflare/workers-types/2022-11-30"

const getAllUsersQuery = `-- name: GetAllUsers :many
select id, screenname, createdat from User`;

export type GetAllUsersRow = {
  id: number;
  screenname: string;
  createdat: string;
};

export async function getAllUsers(
  d1: D1Database
): Promise<D1Result<GetAllUsersRow>> {
  return await d1
    .prepare(getAllUsersQuery)
    .all<GetAllUsersRow>();
}
```

worker.ts

```tsx
export default {
  async fetch(request: Request, env: Env) {
    const { results: users } = await getAllUsers(env.DB);
    return new Response(JSON.stringify(users));
  }
};
```

生成される型は`screenname`のようになっていますが、実際には値がキャメルケースで返ってきます。

```
$ npx wrangler dev
$ curl localhost:8787
[{"id":1,"screenName":"tekihei2317","createdAt":"2023-08-01 10:27:36"}]%
```

### 期待する挙動

GetAllUsersRowの型が、次のようにキャメルケースで生成されること。

```tsx
export type GetAllUsersRow = {
  id: number;
  screenName: string;
  createdAt: string;
};
```

### 補足

sqlcの場合はカラムをスネークケースで定義する必要がある（した方がよい）、オプションを指定すれば解決できる、などあれば教えていただけると嬉しいです。

**Comment by orisano** [comment]
SQLは大文字小文字を無視するので sqlc-gen-ts-d1 ではスネークケースを前提にしています。
(その前提で sqlc 側で小文字で統一されていて plugin 側で対処できない)
SELECT ですべて小文字でも正しい値が返ってきていることからもそれがわかると思います。
SQLiteがカラム名の情報をCREATE TABLEでの定義通りキャメルケースで返しているので正常に動作していません。
sqlc-gen-ts-d1 では DB がスネークケースだと typescript ではキャメルケースで扱えるようにしているため、スネークケースにすることをおすすめします。

**Comment by tekihei2317** [comment]
回答ありがとうございます！
普段使っているORMがDBで定義した通りに返ってくる感じだったので、（それと同じように考えて）TypeScript側で扱いやすいようにキャメルケースにしていました。

> (その前提で sqlc 側で小文字で統一されていて plugin 側で対処できない)

なるほどです...。

> sqlc-gen-ts-d1 では DB がスネークケースだと typescript ではキャメルケースで扱えるようにしているため、

この機能とても助かります。スネークケースでやってみます！
